services:

  talker:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2_humble_demo
    container_name: ros2_talker
    command: >
      /bin/bash -c "
        source /opt/ros/humble/setup.bash &&
        source /ros2_ws/install/setup.bash &&
        ros2 run my_ros2_pkg talker
      "
    networks:
      - ros2_net

  listener:
    image: ros2_humble_demo
    container_name: ros2_listener
    depends_on:
      - talker
    command: >
      /bin/bash -c "
        source /opt/ros/humble/setup.bash &&
        source /ros2_ws/install/setup.bash &&
        ros2 run my_ros2_pkg listener
      "
    networks:
      - ros2_net

networks:
  ros2_net:
    driver: bridge
